[world]
width = 100
height = 40
alive_symbol = "â—"
dead_symbol = " "
speed = 1

[[patterns]]
start_x = 30
start_y = 10
living_cells = [[6, 0], [4, 1], [6, 1], [7, 1], [4, 2], [6, 2], [4, 3], [2, 4], [0, 5], [2, 5]]
